<template>
  <component
    :is="iconComponent"
    :size="size"
    :stroke-width="strokeWidth"
    :color="color || 'currentColor'"
    :class="['icon', `icon-${name}`]"
  />
</template>

<script setup lang="ts">
import { computed } from 'vue'
import {
  Activity,
  AlertCircle,
  Upload,
  AlertTriangle,
  ArrowDown,
  ArrowDownUp,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  Award,
  BadgeCheck,
  Bell,
  BellOff,
  Bookmark,
  BookOpen,
  Book,
  Bot,
  Briefcase,
  Calendar,
  CalendarCheck,
  Check,
  CheckCheck,
  CheckCircle,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ChevronsDown,
  CircleCheckBig,
  Clock,
  Code,
  Compass,
  Copy,
  CornerDownLeft,
  Crown,
  Download,
  Edit,
  Edit2,
  Edit3,
  Eye,
  EyeOff,
  FilePlus,
  FileText,
  Flag,
  Flame,
  Folder,
  Gift,
  GraduationCap,
  Grid,
  Heart,
  HelpCircle,
  Home,
  Image,
  ImagePlus,
  Inbox,
  Info,
  Layers,
  LifeBuoy,
  Lightbulb,
  Link,
  Loader,
  Lock,
  LogOut,
  Mail,
  MapPin,
  Megaphone,
  Menu,
  MessageCircle,
  MessageSquare,
  MoreHorizontal,
  MoreVertical,
  Palette,
  Phone,
  Plus,
  PlusCircle,
  RefreshCw,
  Search,
  Send,
  Settings,
  Share,
  Share2,
  Shield,
  ShieldCheck,
  ShoppingBag,
  Sliders,
  Sparkles,
  Star,
  Tag,
  Target,
  ThumbsUp,
  Ticket,
  TrendingUp,
  Trash,
  Trash2,
  Trophy,
  User,
  UserCheck,
  UserPlus,
  Users,
  WifiOff,
  X,
  XCircle,
  Zap,
} from 'lucide-vue-next'

interface Props {
  name: string
  size?: number | string
  color?: string
  strokeWidth?: number | string
}

const props = withDefaults(defineProps<Props>(), {
  size: 24,
  strokeWidth: 2
})

// name → Lucide 组件映射表（覆盖全项目所有用到的图标名）
const iconMap: Record<string, any> = {
  'activity':           Activity,
  'alert-circle':       AlertCircle,
  'alert-triangle':     AlertTriangle,
  'arrow-down':         ArrowDown,
  'arrow-down-up':      ArrowDownUp,
  'arrow-left':         ArrowLeft,
  'arrow-right':        ArrowRight,
  'arrow-up':           ArrowUp,
  'award':              Award,
  'badge-check':        BadgeCheck,
  'bell':               Bell,
  'bell-off':           BellOff,
  'bookmark':           Bookmark,
  'book':               Book,
  'book-open':          BookOpen,
  'bot':                Bot,
  'briefcase':          Briefcase,
  'calendar':           Calendar,
  'calendar-check':     CalendarCheck,
  'check':              Check,
  'check-check':        CheckCheck,
  'check-circle':       CheckCircle,
  'check-circle-2':     CheckCircle2,
  'circle-check-big':   CircleCheckBig,
  'chevron-down':       ChevronDown,
  'chevron-left':       ChevronLeft,
  'chevron-right':      ChevronRight,
  'chevron-up':         ChevronUp,
  'chevrons-down':      ChevronsDown,
  'clock':              Clock,
  'code':               Code,
  'compass':            Compass,
  'copy':               Copy,
  'corner-down-left':   CornerDownLeft,
  'crown':              Crown,
  'download':           Download,
  'edit':               Edit,
  'edit-2':             Edit2,
  'edit-3':             Edit3,
  'eye':                Eye,
  'eye-off':            EyeOff,
  'file-plus':          FilePlus,
  'file-text':          FileText,
  'flag':               Flag,
  'flame':              Flame,
  'folder':             Folder,
  'gift':               Gift,
  'graduation-cap':     GraduationCap,
  'grid':               Grid,
  'heart':              Heart,
  'heart-pulse':        Heart,
  'help-circle':        HelpCircle,
  'home':               Home,
  'image':              Image,
  'image-plus':         ImagePlus,
  'inbox':              Inbox,
  'info':               Info,
  'layers':             Layers,
  'life-buoy':          LifeBuoy,
  'lightbulb':          Lightbulb,
  'lightning':          Zap,
  'link':               Link,
  'loader':             Loader,
  'lock':               Lock,
  'log-out':            LogOut,
  'mail':               Mail,
  'map-pin':            MapPin,
  'megaphone':          Megaphone,
  'menu':               Menu,
  'message-circle':     MessageCircle,
  'message-square':     MessageSquare,
  'more-horizontal':    MoreHorizontal,
  'more-vertical':      MoreVertical,
  'palette':            Palette,
  'phone':              Phone,
  'plus':               Plus,
  'plus-circle':        PlusCircle,
  'refresh-cw':         RefreshCw,
  'school':             GraduationCap,
  'search':             Search,
  'send':               Send,
  'settings':           Settings,
  'share':              Share,
  'share-2':            Share2,
  'shield':             Shield,
  'shield-check':       ShieldCheck,
  'shopping-bag':       ShoppingBag,
  'sliders':            Sliders,
  'smile':              MessageCircle,
  'sparkles':           Sparkles,
  'star':               Star,
  'star-off':           Star,
  'tag':                Tag,
  'target':             Target,
  'thumbs-up':          ThumbsUp,
  'ticket':             Ticket,
  'trash':              Trash,
  'trash-2':            Trash2,
  'trending-up':        TrendingUp,
  'trophy':             Trophy,
  'upload':             Upload,
  'user':               User,
  'user-check':         UserCheck,
  'user-plus':          UserPlus,
  'users':              Users,
  'wifi-off':           WifiOff,
  'x':                  X,
  'x-circle':           XCircle,
  'zap':                Zap,
}

const iconComponent = computed(() => iconMap[props.name] ?? HelpCircle)
</script>

<style lang="scss" scoped>
.icon {
  display: inline-block;
  vertical-align: middle;
  flex-shrink: 0;
}
</style>
